import { CountExperience, Footer, Hero, Navbar, Portfolio, Testimonials } from '@/components'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fusion Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='py-6'>
        <div className='w-11/12 mx-auto'>
          <Navbar/>
          <Hero/>
          <CountExperience/>
          <Portfolio/>
          <Testimonials/>
          <Footer/>
        </div>
      </main>
    </>
  )
}
